version: '3.8'

services:
  mongodb:
    container_name: mongo
    image: mongo:7.0
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=initdb
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local   